CREATE DATABASE ESTOQUE_DB;

USE ESTOQUE_DB;

CREATE TABLE PRODUTOS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
PRECO DECIMAL(6,2),
CATEGORIA  VARCHAR(100),
QUANTIDADE_ESTOQUE INT
);

INSERT INTO produtos (nome, preco, CATEGORIA,QUANTIDADE_ESTOQUE) VALUES 
('Notebook', 3000.00, "informatica", 10), 
('Mouse', 100.00, "periferico", 8), 
('Teclado', 150.00, "periferico", 6);


select * from PRODUTOS;



